name = "PracticalPkg"
uuid = "f93ac9d6-c0e5-564d-9c20-a1d2b629210c"
version = "0.1.0"
authors = ["mcclellanio mcclellanio@fastmail.com"]

[workspace]
projects = ["test", "docs"]

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Chain = "1.0.0"
GraphRecipes = "0.5.16"
Graphs = "1.13.4"
LaTeXStrings = "1.4.0"
Luxor = "4.4.1"
Plots = "1.41.6"
Primes = "0.5.7"
Random = "1.11.0"
RecipesBase = "1.3.4"
SpecialFunctions = "2.7.1"
UnicodePlots = "3.8.1"
julia = "1.12"
