name = "PracticalPkg"
uuid = "f93ac9d6-c0e5-564d-9c20-a1d2b629210c"
version = "0.1.0"
authors = ["mcclellanio mcclellanio@fastmail.com"]

[workspace]
projects = ["test", "docs"]

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Chain = "1.0.0"
Distributions = "0.25.123"
GraphRecipes = "0.5.16"
Graphs = "1.13.4"
JLD = "0.13.5"
LaTeXStrings = "1.4.0"
Latexify = "0.16.10"
Luxor = "4.4.1"
Measurements = "2.14.1"
Missings = "1.2.0"
Oceananigans = "0.105.0"
Plots = "1.41.6"
Primes = "0.5.7"
Random = "1.11.0"
RecipesBase = "1.3.4"
SpecialFunctions = "2.7.1"
StatsBase = "0.34.10"
UnicodePlots = "3.8.1"
Unitful = "1.28.0"
julia = "1.12"
