name = "PracticalPkg"
uuid = "f93ac9d6-c0e5-564d-9c20-a1d2b629210c"
version = "0.1.0"
authors = ["mcclellanio mcclellanio@fastmail.com"]

[workspace]
projects = ["test", "docs"]

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
LaTeXStrings = "1.4.0"
Plots = "1.41.6"
Random = "1.11.0"
UnicodePlots = "3.8.1"
julia = "1.12"
